#!/bin/bash
################################################################################
# SSH Bash Library
#
# SSH specific routines. These help ssh keep track of sessions amoung other 
# customizations.
#
################################################################################


#################################################################################
# Set Auth Sock
#
# Sets the value of the SSH_AUTH_SOCK variable to the location of the symlink 
# that gets added to ${HOME}/.ssh/ssh_auth_sock ($SSH_AUTH_SOCK_LNIK)
#
#################################################################################
set_auth_sock() {

  if [ ! -S ${SSH_AUTH_SOCK_LINK} ]; then

    rm $SSH_AUTH_SOCK_LINK

    if [ ! -S $SSH_AUTH_SOCK ]; then

       # Make a new socket
       eval $(ssh-agent|grep ^SSH)

    fi

    ln -s $SSH_AUTH_SOCK $SSH_AUTH_SOCK_LINK
    export SSH_AUTH_SOCK="${SSH_AUTH_SOCK_LINK}"

  else

    # This means we may have a dead symbolic link and usually happens with 
    # long duration logins or using terminals multiplexers like tmux or
    # GNU screen.
    test_symlink $SSH_AUTH_SOCK_LINK  $SSH_AUTH_SOCK 1> /dev/null

    if [ "$?" != 0 ]; then 

      rm $SSH_AUTH_SOCK_LINK
      eval $(ssh-agent|grep  ^SSH)
      ln -s $SSH_AUTH_SOCK $SSH_AUTH_SOCK_LINK
      export SSH_AUTH_SOCK="${SSH_AUTH_SOCK_LINK}"

    fi

  fi

  return 0

}

# vim: ft=sh
