#!/bin/bash
################################################################################
# SSH Resouce File
# 
# With some terminal softare there needs to be some resources available from ssh
# to keep them functioning over long periods of time or multiple ssh sessions.
# Homb keeps track of a few enviromental variables that make if easier to track
# multiple logins. The SSH specific variables are stored here.
################################################################################

# Load the ssh function library.
export SSHLIB="${HOMBASE}/ssh/lib" && test -f $SSHLIB && source $SSHLIB

# Place to store the symbolic link to the auth_sock.
export SSH_AUTH_SOCK_LINK=${HOME}/.ssh/ssh_auth_sock

check_auth_sock
