#!/bin/bash
################################################################################
# Git Colors
#
# File that has the different colors used by git
#
################################################################################

export GIT_PS1_COLOR="${Reset}${Bold}${Black}" # All clear
export GIT_PS1_COLOR_UNSTAGED="${Reset}${Bold}${Yellow}" # "*" Modifications are not committed
export GIT_PS1_COLOR_STAGED="${Reset}${Green}" # "+" Added files to stage uncommitted
export GIT_PS1_COLOR_STASHED="${Reset}${Cyan}" # "$" If somethings is stashed.
export GIT_PS1_COLOR_UNTRACKED="${Reset}${Red}" # "%" Files are not being tracked 
