#!/bin/bash
################################################################################
# Git Library
#
# This file contains the library of functions that are called by homb's other
# files specifically for git.
#
################################################################################


################################################################################
# 
# gitPS1
#
# We are going to use this over __get_ps1() because we want to trap errors and 
# customize the output.
#
################################################################################
gitPS1() {

  local git_ps1="$(__git_ps1 2> /dev/null)"

  if [ "${git_ps1}" != "" ]; then 
  
    echo -en "$(__git_ps1 "(%s)")"
    return 0

  else

    # FAILBOAT
    return 1

  fi

}
