#!/bin/bash
################################################################################
#
# git Bash RC File
#
# This file is intended to be the entry point for all things git and bash. 
#
################################################################################

# Variables
#-------------------------------------------------------------------------------
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1

# Includes
#-------------------------------------------------------------------------------
include git/color
include git/completion

# vim:ft=sh
