#!/bin/bash
################################################################################
#
# git Bash RC File
#
# This file is intended to be the entry point for all things git and bash. 
#
################################################################################
include git/completion
include git/color

#if [ -f ~/.gitconfig ]; then
#
#  echo "CHECK: ~/.gitconfig file"
#
#
#else
#
#  echo "ERROR: ~/.gitconfig file (not found)"
#
#fi

export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1


