#!/bin/bash
#################################################################################
# homb
# 
# Reloads Homb for the calling shell. Must have $HOMBASE set! This also runs 
# handles reloading fresh as well.
#
#################################################################################
homb() {

  if [ $HOMBASE != "" ]; then

    local hombRC="${HOMBASE}/rc"

    if [ -f $hombRC ]; then

      source $hombRC

      if [[ "$(which fresh)" ]]; then

        cd $HOME;
        # Use freshtica so we get the paths right.
        freshtica update
        cd $OLDPWD

      fi

      return 0

    else

      echo "FAIL: File not found ($hombRC)"
      return 1

    fi

  else

    echo "FAIL: \$HOMBASE empty or not set."
    exit 13

  fi  

}


################################################################################
#
# hombie
#
# Checks to see that we are indeed running a shell that Homb supports.
#
################################################################################
hombie() {

  local whichBash=$(which bash 2> /dev/null)
  local aliasBash=$(alias bash 2> /dev/null)  

  case $SHELL in

    ${whichBash}|${alaisBash})
      
      return 0
      ;;
    
    *)
      return 1
      ;;

  esac
}


#################################################################################
# 
# locals_only
#
# Looks for the special file $HOMB_LOCAL and sources it.
#
#################################################################################
locals_only() {

  if [ -z "${HOMBLOCAL}" ]; then
  
    local hombrc="${HOME}/.hombrc"
  
    if [ -e "${hombrc}" ]; then 
  
      export HOMBLOCAL="${hombrc}"
  
    fi
  
  fi

  if [ -e "${HOMBLOCAL}" ]; then

    source "${HOMBLOCAL}"

  fi

}


################################################################################
# 
# include
#
# A quick way to include files for the homb project.
#
################################################################################
include() {

  if [ -f "${HOMBASE}/${1}" ];  then

    source "${HOMBASE}/${1}"

  else

    if [ -f "${HOMBASE}/${1}/rc" ]; then
      
      # Load the libraries needed for the resource file.
      # This enforces the default for $1/rc and $1/lib existing.
      if [[ ${1} != *"/"* ]]; then


        local pathLib="${HOMBASE}/${1}/lib"

        if [ -f $pathLib ]; then

          source $pathLib

        fi

        local pathAlias="${HOMBASE}/${1}/alias"

        if [ -f $pathAlias ]; then

          source $pathAlias

        fi

        local pathCompletion="${HOMBASE}/${1}/completion"

        if [ -f $pathCompletion ]; then

          source $pathCompletion

        fi

      fi

      source "${HOMBASE}/${1}/rc"

    fi
  fi
}
