#!/bin/bash
# .homb resource file
################################################################################
#
# Homb Specifics
# 
# !!!! WARNING !!! WARNING !!! WARNING !!! WARNING !!! WARNING !!! WARNING !!!!
#
# $HOMBASE MUST BE SET! The global environment variable HOMBASE is required for
# Homb to load and work correctly. HOMBASE is the root of the Homb project.
#
# Example 1) Typical shell install.
#
#    ~/.bash_profile (not ~/.bashrc)
#    export HOMBASE="${HOME}/.homb" # NO TRAILING SLASH!!!
#
# !!!! WARNING !!! WARNING !!! WARNING !!! WARNING !!! WARNING !!! WARNING !!!!
#
#
################################################################################

# Homb depends on bash as the shell. (it's the B in HomB) To get started we need
# to load the bashlib library and use its magics.
export HOMBLIB="${HOMBASE}/lib" && test -e $HOMBLIB && source $HOMBLIB

# If you're not a hombie then you have to leave.
hombie 2> /dev/null || return;

################################################################################
# Bash 
################################################################################
include bash

################################################################################
# Application Resources !!!WARNING!!!   ORDER MATTERS... srsly.    !!!WARNING!!!
################################################################################
include ssh
include git
include tmux

if [ -z "$HOMBLOCAL" ]; then

  HOMBLOCAL="${HOME}/.hombrc"

fi

# Must be called last
locals_only
