#!/bin/bash

# Fixes an issue with fresh not running from the home directory. This is an
# alias for fresh in the alias file.
freshtica(){

  local work=$PWD;

  cd ${HOME}

  if [ -x ${HOME}/bin/fresh ]; then

    ${HOME}/bin/fresh $@

  fi

  cd $work

}
