#!/bin/bash

# include test  
include-test0(){

  if [ -f "${HOMBASE}/${1}" ];  then
    source "${HOMBASE}/${1}"
  else
    if [ -f "${HOMEBASE}/${1}/rc" ]; then
      source "${HOMBASE}/${1}/rc"
    else
      return 1 #fail
    fi
  fi

}

include-test0 drush

echo -en "Test Completed: "

if [ $? ]; then

  echo -e "${Green}Success."
  exit 0;

else

  echo -e "${Red}Fail."
  exit 1;

fi
# vim:ft=sh
