#!/bin/bash
################################################################################
# TMux Functions
################################################################################

################################################################################
# tomb
#
# Alias for tmux attach-session -t [$1], but will connect to the first session.
# TODO Add logic for multiple sessions and prompt the user for the correct one.
#
################################################################################
tomb() {

  if [ -z "${1}" ]; then

    local session_ls=$(tmux list-sessions 2> /dev/null|cut -f 1 -d\:)

    if [ -z "${session_ls}" ]; then 

      set_auth_sock
      sleep 1s
      TERM=xterm-256color
      tmux -2 new-session -s "$(hostname -s)"
      return 0

    else

      local count=$(($(echo -ne "$session_ls"|wc -l) + 1))

      if [[  "$count" > "1" ]]; then

        # Generate a list of tombs
        local current=0
        IFS=$'\n'
        sessions="$(tmux list-sessions 2> /dev/null)"
        declare -a targets=()

        for item in $sessions; do

          title=$(echo "${item}"|cut -f 1 -d\:)
          properties=$(echo "${item}"|cut -f 2- -d\:)

          targets[$current]=$title
          current=$(($current + 1))

        done

        PS3="Pick a tomb to ressurect (${count} found):"
        safe_word="Quit"

        select option in "${targets[@]}" "Quit"; do

          if [ ! -z "${targets[$((${REPLY} - 1 ))]}" ]; then
               
            # if they request to to quit.. using the safeword.
            session_target="${targets[$((${REPLY} - 1))]}"

          else

            echo "else:${targets[$((${REPLY} - 1))]}"

          fi
        done

      else
        # Ressurect the solo tomb
        session_target=$session_ls
      fi

      echo "Resurrecting $session_target"
      sleep 1s
      TERM=xterm-256color
      set_auth_sock
      tmux -2 attach-session -t ${session_target}

    fi

  else

    session_ls=$(tmux list-sessions 2> /dev/null|cut -f 1 -d\:|grep $1)

    if [ -z $session_ls ]; then

      echo "Tomb ${1} not found."
      sleep 1s
      set_auth_sock
      TERM=xterm-256color
      tmux -2 new-session -s $1


    else

      echo "Ressurecting ${session_ls}"
      sleep 1s
      set_auth_sock
      TERM=xterm-256color
      tmux -2 attach-session -t $1
 
    fi

  fi
}
