#!/bin/bash
################################################################################# drush/rc
#
# This is the main bash resource file for drush. 
################################################################################

include drush/completion

# vim:ft=sh
