#!/bin/bash

################################################################################
# Colors
#
# File that contains all the local colors in semi easy to use strings. Thse can
# be mixed together to get the desired color intensity and background.
#
################################################################################

[[ -t 2 && $TERM != dumb ]] && {


  # Dimensions
  #-------------------------------------------------------------------------------
  # Columns in a line
  COL=$({ tput cols || tput co} 2>&3)
  # Lines in the screen 
  ROW=$({ tput lines || tput li} 2>&3)

  # Controls
  #-------------------------------------------------------------------------------
  # Reset 
  Reset=$(tput sgr0 || tput me)
  # Bold
  Bold=$(tput bold || tput md ) 

  # Basic Colors
  #-------------------------------------------------------------------------------
  # Black
  Black=$(tput setaf 0 || tput AF 0)   
  # White
  White=$(tput setaf 7 || tput AF 7)

  # Fancy Colors
  #-------------------------------------------------------------------------------
  [[ $TERM != *-m ]] && {
    # Red
    Red=$(tput setaf 1 || tput AF 1)
    # Green
    Green=$(tput setaf 2 || tput AF 2)
    # Yellow
    Yellow=$(tput setaf 3 || tput AF 3)
    # Blue
    Blue=$(tput setaf 4 || tput AF 4)
    # Purple
    Purple=$(tput setaf 5 || tput AF 5)
    # Cyan
    Cyan=$(tput setaf 6 || tput AF 6)
  } 
 
  # Bold Colors 
  #-------------------------------------------------------------------------------
  # Bold Black
  BBlack=$(tput setaf 0; tput bold)
  # Bold Red
  BRed=$(tput setaf 1; tput bold)
  # Bold Green
  BGreen=$(tput setaf 2; tput bold)
  # Bold Yellow
  BYellow=$(tput setaf 3; tput bold)
  # Bold Blue
  BBlue=$(tput setaf 4; tput bold)
  # Bold Purple
  BPurple=$(tput setaf 5; tput bold)
  # Bold Cyan
  BCyan=$(tput setaf 6; tput bold)
  # Bold White
  BWhite=$(tput setaf 7; tput bold)
  
  
#  # Underline
#  UBlack='\e[4;30m'       # Black
#  URed='\e[4;31m'         # Red
#  UGreen='\e[4;32m'       # Green
#  UYellow='\e[4;33m'      # Yellow
#  UBlue='\e[4;34m'        # Blue
#  UPurple='\e[4;35m'      # Purple
#  UCyan='\e[4;36m'        # Cyan
#  UWhite='\e[4;37m'       # White
#  
#  # Background
#  On_Black='\e[40m'       # Black
#  On_Red='\e[41m'         # Red
#  On_Green='\e[42m'       # Green
#  On_Yellow='\e[43m'      # Yellow
#  On_Blue='\e[44m'        # Blue
#  On_Purple='\e[45m'      # Purple
#  On_Cyan='\e[46m'        # Cyan
#  On_White='\e[47m'       # White
#  
#  # High Intensity
#  IBlack='\e[0;90m'       # Black
#  IRed='\e[0;91m'         # Red
#  IGreen='\e[0;92m'       # Green
#  IYellow='\e[0;93m'      # Yellow
#  IBlue='\e[0;94m'        # Blue
#  IPurple='\e[0;95m'      # Purple
#  ICyan='\e[0;96m'        # Cyan
#  IWhite='\e[0;97m'       # White
#  
#  # Bold High Intensity
#  BIBlack='\e[1;90m'      # Black
#  BIRed='\e[1;91m'        # Red
#  BIGreen='\e[1;92m'      # Green
#  BIYellow='\e[1;93m'     # Yellow
#  BIBlue='\e[1;94m'       # Blue
#  BIPurple='\e[1;95m'     # Purple
#  BICyan='\e[1;96m'       # Cyan
#  BIWhite='\e[1;97m'      # White
#  
#  # High Intensity backgrounds
#  On_IBlack='\e[0;100m'   # Black
#  On_IRed='\e[0;101m'     # Red
#  On_IGreen='\e[0;102m'   # Green
#  On_IYellow='\e[0;103m'  # Yellow
#  On_IBlue='\e[0;104m'    # Blue
#  On_IPurple='\e[0;105m'  # Purple
#  On_ICyan='\e[0;106m'    # Cyan
#  On_IWhite='\e[0;107m'   # White
}

if [ "${TERM_PROGRAM}" == "Apple_Terminal" ]; then
  export CLICOLOR=1
  export LSCOLORS=ExFxBxDxCxegedabagacad
fi
