#!/bin/bash

################################################################################
# Colors
#
# File that contains all the local colors in semi easy to use strings. Thse can
# be mixed together to get the desired color intensity and background.
#
################################################################################

[[ -t 2 && $TERM != dumb ]] && {

  # Dimensions
  #-------------------------------------------------------------------------------
  # Columns in a line
  COLS=$({ tput cols || tput co;} 2> /dev/null)
  # Lines in the screen 
  ROWS=$({ tput lines || tput li;} 2> /dev/null)

  # Controls
  #-------------------------------------------------------------------------------
  # Reset 
  Reset=$({ tput sgr0 || tput me;} 2> /dev/null)
  # Bold
  Bold=$({ tput bold || tput md;} 2> /dev/null)
  # Blink
  Blink=$({ tput blink || tput mb;} 2> /dev/null)

  # Basic Colors
  #-------------------------------------------------------------------------------
  # Black
  Black=$({ tput setaf 0 || tput AF 0;} 2> /dev/null)   
  # White
  White=$({ tput setaf 7 || tput AF 7;} 2> /dev/null)

  # Fancy Colors
  #-------------------------------------------------------------------------------
  [[ $TERM != *-m ]] && {
    # Red
    Red=$({ tput setaf 1 || tput AF 1;} 2> /dev/null)
    # Green
    Green=$({ tput setaf 2 || tput AF 2)
    # Yellow
    Yellow=$(tput setaf 3 || tput AF 3)
    # Blue
    Blue=$(tput setaf 4 || tput AF 4)
    # Purple
    Purple=$(tput setaf 5 || tput AF 5)
    # Cyan
    Cyan=$(tput setaf 6 || tput AF 6)
  } 
 
  # Bold Colors 
  #-------------------------------------------------------------------------------
  # Bold Black
  BBlack=$(tput setaf 0; tput bold)
  # Bold Red
  BRed=$(tput setaf 1; tput bold)
  # Bold Green
  BGreen=$(tput setaf 2; tput bold)
  # Bold Yellow
  BYellow=$(tput setaf 3; tput bold)
  # Bold Blue
  BBlue=$(tput setaf 4; tput bold)
  # Bold Purple
  BPurple=$(tput setaf 5; tput bold)
  # Bold Cyan
  BCyan=$(tput setaf 6; tput bold)
  # Bold White
  BWhite=$(tput setaf 7; tput bold)

}

if [ "${TERM_PROGRAM}" == "Apple_Terminal" ]; then
  export CLICOLOR=1
  export LSCOLORS=ExFxBxDxCxegedabagacad
fi
