#!/bin/bash
#################################################################################
# ~/.homb/bash/ps1
#
# This file contains the configuration information for the bash prompt.
#
#################################################################################

#################################################################################
# Defaults
#################################################################################

# Color Defaults
#--------------------------------------------------------------------------------

# Username Color
if [ -z "${COLOR_USER}" ]; then
  COLOR_USER="${Bold}${Green}"
fi

# Super User Color (UID 0)
if [ -z "${COLOR_SUDO}" ]; then
  COLOR_SUDO="${Bold}${Yellow}"
fi

# Path Color
if [ -z "${COLOR_PATH}" ]; then
  COLOR_PATH="${Green}"
fi

# Hostname Color
if [ -z "${COLOR_HOST}" ]; then
  COLOR_HOST="${Bold}${White}"
fi

# Pick the prompt based on the system
#------------------------------------------ -------------------------------------
PROMPT_BASIC='\u@\h \$ ' # Basic prompt for compatability

# color(ColorName, "target_string") *shrug* 
PROMPT_USER='\[${COLOR_USER}\]\u\[${Reset}\]@\[${COLOR_HOST}\]\h\[${Reset}\][\[${COLOR_PATH}\]\w\[${Reset}\]]$(gitPS1)\[${Reset}\]\n\$ '; 

PROMPT_SUDO='\[${COLOR_SUDO}\]\u\[${Reset}\]@\[${COLOR_HOST}\]\h\[${Reset}\][\[${COLOR_PATH}\]\w\[${Reset}\]]$(gitPS1)\[${Reset}\]\n\$ '; 

# Switch the prompt based on the (TODO terminal and) user we are using.
#-------------------------------------------------------------------------------
if [ $(interactive) ]; then

  # Load  prompt for the super user
  #---------------------------------------------------------------------------
  if [[ "${UID}" == "0" ]]; then
      
    PS1=$PROMPT_SUDO

  else

    PS1=$PROMPT_USER

  fi
      
else

  PS1=$PROMPT_BASIC

fi
