#!/bin/bash
###############################################################################
# Bash Shell Resouce File
#
# Contains all the magic for Bash shell with Homb. This all pivots on what is 
# set in the "HOMBASE" variable. All the functions are defined in 
# $HOMBASE/bashlib for this file.
#
###############################################################################

################################################################################
#  Homb Specifics
# 
# Configurations required by Homb to load and work correctly. HOMBASE is the 
# root of # the Homb project (ie. ~/.homb)  This is put here rather than have
# bash application specifics in a "homb" specific file.
#
################################################################################
export HOMBASE="${HOME}/.homb" # NO GD TRAILING SLASH!!!

# Load the bashlib library - Gives us all the other helpers and files for bash.
export BASHLIB="${HOMBASE}/bash/lib" && test -f $BASHLIB && source $BASHLIB

# Not teh bash, not happy.
bash_happy|| return;

################################################################################
# Application Resources !!!WARNING!!!   ORDER MATTERS... srsly.    !!!WARNING!!!
################################################################################
include ssh
include git
include svn
include tmux/completion
include drush

################################################################################
# Main user
#
# User customizations and semi-os specific application environment stuff.
#
################################################################################
umask 0002


################################################################################
# Main user's variables
################################################################################
export EDITOR="vim"
export LANG="en_US.UFT-8"
export LC_ALL="C"
export PAGER="less"
export PROMPT_DIRTRIM=3

# Helpers for later use
#-------------------------------------------------------------------------------
export DISPLAY_CONNECT="${DISPLAY}"

# History 
#-------------------------------------------------------------------------------
export HISTTIMEFORMAT="%F %T - "
export HISTFILESIZE="4000000"
export HISTSIZE="4000000"
export HISTCONTROL="ignoredups"

# irc
#-------------------------------------------------------------------------------
export IRCNAME="Federal Holiday"


################################################################################
# Export the path (important)
################################################################################
export PATH=$PATH

# Include other resource files - The order matters... SRSLY :-\
#-------------------------------------------------------------------------------
include bash/alias
include bash/color
include bash/ps1

# Local resouces, not loaded if they are not there, loaded last to overide all.
include home
include work


# vim:ft=sh
